# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./headers/Intersections.h \
    ./headers/SegmentContainer.h \
    ./headers/Graph.h

#Source files
SOURCES += ./src/Intersections.cpp \
    ./src/main.cpp \
    ./src/SegmentContainer.cpp \
    ./src/Graph.cpp
